/* Two rows of structure and jurisdiction stamps (marquee driven by SpvMotion). Converted from the structuring landing page HTML. */
export function SpvStamps() {
  return (
    <>
<div className="stamps" aria-label="Structures and jurisdictions we advise on">
  <div className="st-row" data-dir="-1"><div className="st-t"><span className="sp"><em><i>01</i></em>Private foundations</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>02</i></em>Holding companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>03</i></em>SPVs</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>04</i></em>Offshore companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>01</i></em>Private foundations</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>02</i></em>Holding companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>03</i></em>SPVs</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>04</i></em>Offshore companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>01</i></em>Private foundations</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>02</i></em>Holding companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>03</i></em>SPVs</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>04</i></em>Offshore companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>01</i></em>Private foundations</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>02</i></em>Holding companies</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>03</i></em>SPVs</span><b className="sx" aria-hidden="true"></b><span className="sp"><em><i>04</i></em>Offshore companies</span><b className="sx" aria-hidden="true"></b></div></div>
  <div className="st-row" data-dir="1"><div className="st-t"><span className="sp j"><em><i>DI</i></em>DIFC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>AD</i></em>ADGM</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DM</i></em>DMCC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>RK</i></em>RAK ICC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>JZ</i></em>JAFZA Offshore</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DI</i></em>DIFC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>AD</i></em>ADGM</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DM</i></em>DMCC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>RK</i></em>RAK ICC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>JZ</i></em>JAFZA Offshore</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DI</i></em>DIFC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>AD</i></em>ADGM</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DM</i></em>DMCC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>RK</i></em>RAK ICC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>JZ</i></em>JAFZA Offshore</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DI</i></em>DIFC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>AD</i></em>ADGM</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>DM</i></em>DMCC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>RK</i></em>RAK ICC</span><b className="sx" aria-hidden="true"></b><span className="sp j"><em><i>JZ</i></em>JAFZA Offshore</span><b className="sx" aria-hidden="true"></b></div></div>
  <span className="st-badge" aria-hidden="true"><i></i>We advise on</span>
</div>
    </>
  );
}
